In [1]:
import numpy as pd

a = np.arange(1,11)

In [2]:
a = np.arange(1,11)

NameError: name 'np' is not defined

In [3]:
import numpy as np


In [4]:
a = np.arange(1,11)

In [5]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
b = np.arange(21, 31)

In [7]:
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [8]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [9]:
a-b

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [10]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [12]:
a/b

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [13]:
a**b

array([                  1,             4194304,         94143178827,
           281474976710656,  298023223876953125, 4561031516192243712,
       5059972980857283351,                   0, 5756027422282277481,
       5076944270305263616])

In [14]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
my_str = "Mexico is nice"

In [16]:
my_str.index("is")

7