Another less than 2 hrs course from Terezija Semenski, at LinkedIn

### Numpy Essential Training

In [1]:
import numpy as np

In [2]:
a = np.arange(1, 11)

In [3]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
b = np.arange(21, 31)

In [5]:
print(b)

[21 22 23 24 25 26 27 28 29 30]


# Lists & Arrays

In [6]:
print(type(b))

<class 'numpy.ndarray'>


## Array types and conversions between types

In [7]:
integers = np.array(10, 50, 10)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
integers = np.array([10, 20, 30, 40, 50])

In [9]:
print(integers)

[10 20 30 40 50]


In [10]:
print(integers[0])

10


In [11]:
integers[0] = 20

In [12]:
print(integers)

[20 20 30 40 50]


In [13]:
integers[0] = 20.5

In [14]:
integers

array([20, 20, 30, 40, 50])

In [15]:
integers.dtype

dtype('int64')

In [17]:
smaller_integers = np.array(integers, dtype=np.int8)
smaller_integers

array([20, 20, 30, 40, 50], dtype=int8)

In [18]:
integers.nbytes
smaller_integers.nbytes

5

In [19]:
integers.nbytes

40

In [20]:
array([127, -128, -127], dtype=np.int8)

NameError: name 'array' is not defined

In [22]:
overflow = np.array([127, 128, 129], dtype=np.int8)

In [23]:
overflow

array([ 127, -128, -127], dtype=int8)

In [24]:
overflow.nbytes

3

In [25]:
floats = np.array([1.2, 2.3, 3.4, 5.1, 8.3])

In [26]:
floats.dtype

dtype('float64')

## Multidimensional Arrays

### Two-dimensional Arrays

In [28]:
nums = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
nums[0][-1]

5

In [36]:
nums[1][-1]
nums[1, -1]
nums[1, 1]

7

In [31]:
nums.ndim

2

### Multi-dimensional Array

In [32]:
multi_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [33]:
multi_arr.ndim

3

In [34]:
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
multi_arr[1, 0, 2]

9

## Arrays from lists and other Python structures

In [38]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
arr = np.array(lst)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
second_lst = [1, 2, 3, -1.23, 50, 128000.58, 56, 4.56]

In [42]:
second_arr = np.array(second_lst)

In [43]:
second_arr

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800058e+05,  5.6000000e+01,  4.5600000e+00])

In [44]:
second_arr.dtype

dtype('float64')

In [45]:
first_tuple = (5, 10, 15, 20, 25, 30)

In [46]:
arr_from_tuple = np.array(first_tuple)

In [47]:
arr_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [48]:
arr_from_tuple.dtype

dtype('int64')

## Intrinsic NumPy array creating

## Reshaping arrays

In [108]:
reshape_arr = np.arange(1, 13)

In [109]:
reshape_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [110]:
r_arr = np.reshape(reshape_arr, (3,4))

In [111]:
r_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
arr6 = np.array([[1, 2],[3, 4],[5, 6]])

In [113]:
arr6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [114]:
flat_arr = np.reshape(arr6, -1)

In [115]:
flat_arr

array([1, 2, 3, 4, 5, 6])