In [4]:
import numpy as np

## Adding, removing and sorting elements

In [2]:
arr1 = np.array([1,2,3,5])

In [3]:
arr1

array([1, 2, 3, 5])

In [4]:
new_arr1 = np.insert(arr1, 3, 4)

In [5]:
new_arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([1,2,3,4])

In [7]:
arr2

array([1, 2, 3, 4])

In [8]:
new_arr2 = np.append(arr2, 5)

In [9]:
new_arr2

array([1, 2, 3, 4, 5])

## Aggregate Functions


In [5]:
arr3 = np.arange(10, 110, 10)
arr3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
arr4 = np.arange(10, 100, 10).reshape(3,3)
arr4

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
arr5 = np.arange(10, 110, 10).reshape(2,5)

In [16]:
arr5

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [17]:
arr3.sum()

550

In [18]:
arr4.sum()

450

In [19]:
arr5.sum()

550

In [20]:
arr3.sum(axis=0)

550

In [22]:
arr4.sum(axis=1)

array([ 60, 150, 240])

In [23]:
even_arr = np.arange(1, 11)

In [24]:
even_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
even_arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
even_arr[even_arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [7]:
arr3.prod()

36288000000000000

## Get unique items and counts

In [8]:
unique_arr = np.array([1, 2, 3, 3, 4, 5, 6, 6, 6, 8, 7, 9, 10])

In [9]:
np.unique(unique_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr7 = np.arange(12).reshape((3,4))

In [11]:
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.transpose(arr7)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])