In [1]:
import numpy as np

## Adding, removing and sorting elements

In [2]:
arr1 = np.array([1,2,3,5])

In [3]:
arr1

array([1, 2, 3, 5])

In [4]:
new_arr1 = np.insert(arr1, 3, 4)

In [5]:
new_arr1

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([1,2,3,4])

In [7]:
arr2

array([1, 2, 3, 4])

In [8]:
new_arr2 = np.append(arr2, 5)

In [9]:
new_arr2

array([1, 2, 3, 4, 5])